### ISSUE TITLE
Running Proguard on Springboot jars

### ISSUE THREAD

**Issue by peterkronenberg** [wvengen/proguard-maven-plugin#168]
As I play around more with Proguard, I'm learning that it doesn't properly support the BOOT-INF directory that Spring creates in the jar.  I've found a manual process that works, which requires extracting the contents of the BOOT-INF, running Proguard on those files and then putting the jar back together. 
Does the plugin support doing anything like this?  Does anyone have a configuration that works for Springboot?

**Comment by lasselindqvist** [comment]
This plugin is just a real thin wrapper around the Proguard library.
But what you need could perhaps be achieved automatically.

https://maven.apache.org/plugins/maven-dependency-plugin/examples/unpacking-artifacts.html
is able to extract files from JAR/ZIP packages. Then you can run this plugin on that content.
And finally you could run http://maven.apache.org/plugins/maven-assembly-plugin/ to package the things back to a JAR file.

**Comment by lasselindqvist** [comment]
I don't know Spring Boot that well, but it is probably also possible the change the order of the execution of this plugin and the Spring Boot plugins so that this obfuscates the things just before packaging the BOOT-INF directory.
Seeing the pom.xml and possibly the execution logs would help with that.
