### ISSUE TITLE
Is there a possibility of disabling proguard task by passing a JVM property from terminal?

### ISSUE THREAD

**Issue by rmrodrigues** [wvengen/proguard-maven-plugin#52]
Is there a possibility of disabling proguard task by passing a JVM property from terminal?

Something like this -Dproguard.skip=true

Cheers,
Rui Rodrigues.

**Comment by FibreFoX** [comment]
This is no JVM-property, it is a maven-property ;)

Actually it already should skip when calling via `mvn clean package -Dproguard.skip=true`, because thats registered inside the Mojo: https://github.com/wvengen/proguard-maven-plugin/blob/6ca60a36e4453ad1c022e915e4f9ddad9ddf6b80/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L66

Another way would to create a separate maven-profile, which gets disabled when your property was provided

**Comment by rmrodrigues** [comment]
Thank you for your reply.
I've tried with  -Dproguard.skip=true as you said but proguard is running. The property doesn't has effect.
Any suggestion?

**Comment by FibreFoX** [comment]
@rmrodrigues Can you try to create some [mcve](http://stackoverflow.com/help/mcve) for this?

**Comment by FibreFoX** [comment]
@rmrodrigues ;) you might want to close this too ... maybe

**Comment by rmrodrigues** [comment]
Thanks.
